### ISSUE TITLE
Error Message "Could not reach the server" on mounting to FastAPI

### ISSUE THREAD

**Issue by sajsax10** [Chainlit/chainlit#1330] opened 2024-09-10 18:27 UTC
**Describe the bug**
When trying to run Chainlit mounted on FastAPI , the Chainlit app seems to be failing on the path "/chainlit" with the error message:

> Could Not Reach the Server

Accompanied by this in the terminal: 

> Translated markdown file for en-US not found. Defaulting to chainlit.md.

The Chainlit app runs perfectly fine when run separately.

**To Reproduce**
Error observed for Chainlit v1.1.404, normal behavior for v1.1.400

Mounting chainlit on FastAPI app
`mount_chainlit(app=app, target="chatbot/chatbot.py", path="/chainlit")`

Run FastAPI app:

` uvicorn main:app --host 0.0.0.0 --reload`

**Expected behavior**
App should be served as expected unless I'm doing something wrong

**Desktop (please complete the following information):**

- OS: Windows10
- Browser: Chrome
- Version 128.0.6613.120

**Comment by stephenrs** [comment] 2024-09-11 16:22
@sajsax10 Since you are specifying a path, this is likely related to #1313, #1262, and #1317

As far as I'm aware the last release that didn't have this critical bug was 1.1.402, but unfortunately the Chainlit company doesn't seem to be taking it very seriously :(

**Comment by dokterbob** [comment] 2024-09-13 11:52
@stephenrs We are. Please refrain from attacking us, it's unpleasant and unproductive. We appreciate your support but please be aware that we are doing are very best with the bandwidth we have.

@sajsax10 @stephenrs Could you please try and validate whether #1337 resolves your issue?

**Comment by stephenrs** [comment] 2024-09-13 15:37
@dokterbob I'm not attacking you, I'm pointing out my observations, and I'm glad to see you're finally showing some indications that you're paying attention to critical issues like this one.

I would recommend that you get your emotions under control, and stop whining and being so defensive. None of this is personal. Focus on the work and smile about it :)

**Comment by stephenrs** [comment] 2024-09-13 18:37
@dokterbob Just a quick follow-up. You seem to spend a considerable amount of time thinking about and talking about how you feel. So, I think it would be helpful for you to devote some time to thinking about how people in this community feel as a result of your actions, inactions, or lack of communication.

People who encountered this particular problem were completely blocked on their entire project if they didn't know they could downgrade to 1.1.402. This is likely an actual crisis for some people. So, I'm thinking about them and how they feel and doing my best to make sure they are informed about where your priorities appear to be so they don't get stuck in a crisis situation - because that feels terrible.

Also, if you guys make it to the point of having paying customers, what people are going to be saying here is quite likely going to be much more emotionally triggering than anything you'll hear from me - and they won't be focused on helping anyone except themselves. Clearly, my interest is in helping you and the community. So, it might best serve your interests to start thinking about us as customers - OUR happiness is more important than yours, such is the nature of the real world of business.

**Comment by dokterbob** [comment] 2024-09-16 13:59
Closing this as the case as the reproduction seems to fully match the example https://docs.chainlit.io/integrations/fastapi which was tested to be resolved by #1337. Very l33t, much wow.

We're doing a release today.

**Closed** 2024-09-16 13:59 UTC
Labels: needs-triage

**Comment by stephenrs** [comment] 2024-09-16 16:27
> Cool. Note there's 355 issues that YOU can see. There's a bunch you can't see.

Not sure how this is relevant...and maybe if you communicated your priorities or didn't ignore questions about them it wouldn't matter at all which issues are public and which are not.

> Sending long write ups don't help there, it detracts from limited bandwidth we have.

More whining. Wow. 

But hopefully you're learning that when you tell lies about the status of a product (which is illegal in the EU), your "limited bandwidth" is of no concern to the public you lied to and they don't owe you anything. The debt is entirely yours to deliver what you have promised or face worse consequences than people who "annoy" you.

Glad to see some energy and some focus on helping the people of this community get their work done, however.
