### ISSUE TITLE
Getting the Import Error issue

### ISSUE THREAD

**Issue by adithyaboyapati** [Chainlit/chainlit#143] opened 2023-07-06 18:09 UTC
ImportError: dlopen(/Users/users/anaconda3/envs/env1/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

**Comment by willydouhard** [comment] 2023-07-06 18:53
Looks like a duplicate of https://github.com/Chainlit/chainlit/issues/56

**Closed** 2023-07-07 13:45 UTC
