### ISSUE TITLE
TypeError: 'metadata' is a field but has no type annotation

### ISSUE THREAD

**Issue by sivaprasad49** [Chainlit/chainlit#721] opened 2024-02-02 23:43 UTC
When we pip install with Python 3.9** We getting below error.

(venv_llm) C:\******\venv_llm\Scripts>chainlit hello
Traceback (most recent call last):
  File "C:\Users\sn094365\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sn094365\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\******\venv_llm\Scripts\chainlit.exe\__main__.py", line 4, in <module>
  File "c:\******\venv_llm\lib\site-packages\chainlit\__init__.py", line 27, in <module>
    from chainlit.element import (
  File "c:\******\venv_llm\lib\site-packages\chainlit\element.py", line 9, in <module>
    from chainlit.data import get_data_layer
  File "c:\******\venv_llm\lib\site-packages\chainlit\data\__init__.py", line 12, in <module>
    from chainlit.user import PersistedUser, User, UserDict
  File "c:\******\venv_llm\lib\site-packages\chainlit\user.py", line 31, in <module>
    class PersistedUser(User, PersistedUserFields):
  File "c:\******\venv_llm\lib\site-packages\pydantic\dataclasses.py", line 243, in dataclass
    return create_dataclass(_cls)
  File "c:\******\venv_llm\lib\site-packages\pydantic\dataclasses.py", line 218, in create_dataclass
    cls = dataclasses.dataclass(  # type: ignore[call-overload]
  File "C:\******\AppData\Local\Programs\Python\Python39\lib\dataclasses.py", line 1021, in dataclass
    return wrap(cls)
  File "C:\******\AppData\Local\Programs\Python\Python39\lib\dataclasses.py", line 1013, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "C:\******\AppData\Local\Programs\Python\Python39\lib\dataclasses.py", line 887, in _process_class
    raise TypeError(f'{name!r} is a field but has no type annotation')
TypeError: 'metadata' is a field but has no type annotation

**Comment by willydouhard** [comment] 2024-02-03 08:44
This is caused by the latest pydantic released. They fixed in in their latest pre release version, so either install the pre release or downgrade pydantic

**Closed by willydouhard** 2024-02-03 08:44 UTC
