### ISSUE TITLE
[Azure AD OAuth] AADSTS90013: Invalid input received from the user.

### ISSUE THREAD

**Issue by Hayato-Kosugi** [Chainlit/chainlit#438] opened 2023-10-01 09:24 UTC
Occasionally, Azure AD OAuth fails with an error: "[AADSTS90013: Invalid input received from the user."

This issue might be due to random_secret generating strings containing characters that are not URL-safe.

https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/server.py#L302

![image](https://github.com/Chainlit/chainlit/assets/76547305/b0719765-60c8-4e9e-80fe-a47eededd8cd)

**Comment by willydouhard** [comment] 2023-10-01 13:28
Thank you for the feedback! Can you take a look a this @tpatel?

**Comment by clementsirieix** [comment] 2023-10-02 09:24
@Hayato-Kosugi 
We are investigating but we are not able to reproduce on our end.
Could you provide us with more information, for example what's the `random_secret` value that is responsible for the issue?

**Comment by willydouhard** [comment] 2023-10-02 10:44
> @Hayato-Kosugi We are investigating but we are not able to reproduce on our end. Could you provide us with more information, for example what's the `random_secret` value that is responsible for the issue?

You might be able to find it in the browser's cookies. It is stored in the cookies and then deleted on success. Since it is failing it should still be there.

**Comment by clementsirieix** [comment] 2023-10-02 14:44
The bug should be fixed with #442

**Closed by clementsirieix** 2023-10-02 14:44 UTC
