### ISSUE TITLE
Installation difficultities

### ISSUE THREAD

**Issue by BlackDoDo** [Chainlit/chainlit#353] opened 2023-09-04 09:17 UTC
On Macbook Air, after installing chainlit (pip install chainlit), tried chainlit hello. Then I got an error message:

ImportError: dlopen(.....site-packages/grpc/_cython/cygrpc.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

How to solve this?

**Comment by willydouhard** [comment] 2023-09-04 09:36
This looks like a duplicate of https://github.com/Chainlit/chainlit/issues/56

**Closed** 2023-09-05 07:30 UTC
